"""add deleted_at to lists

Revision ID: c31fcc2d37d1
Revises: daf6d081e80f
Create Date: 2026-08-02 00:39:44.634006+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c31fcc2d37d1"
down_revision: str | None = "daf6d081e80f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lists", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_lists_deleted_at"), "lists", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lists_deleted_at"), table_name="lists")
    op.drop_column("lists", "deleted_at")
    # ### end Alembic commands ###
