"""add user activation, session version, last_login_at

Revision ID: c3fb686e27a4
Revises: ab1a1d72af10
Create Date: 2026-07-12 22:27:03.272262+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3fb686e27a4"
down_revision: str | None = "ab1a1d72af10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("session_token_version", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "session_token_version")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
